# Helm values for retail-store-sample-app
namespace: retail-app

tags:
  - Project: Bedrock

postgresql:
  replicaCount: 1

mysql:
  replicaCount: 1

redis:
  replicaCount: 1

rabbitmq:
  replicaCount: 1

ui:
  endpoints:
    catalog: http://retail-app-catalog:80
    carts: http://retail-app-carts:80
    checkout: http://retail-app-checkout:80
    orders: http://retail-app-orders:80
    assets: http://retail-app-assets:80
